apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: tf-text-clf-serve
  annotations:
    scenarios.ai.sap.com/description: "Tensor flow text classification"
    scenarios.ai.sap.com/name: "Milton Movie Review Scenario"
    executables.ai.sap.com/description: "Tensor flow GPU Serving executable"
    executables.ai.sap.com/name: "Milton Movie Review Serving Executable"
  labels:
    scenarios.ai.sap.com/id: "tf-text-clf"
    ai.sap.com/version: "4.0.0"
spec:
  inputs:
    artifacts:
    - name: modelArtifact
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      labels: |
        ai.sap.com/resourcePlan: infer.s
    spec: |
      predictor:
        imagePullSecrets:
          - name: milton-credentials
        containers:
        - name: kfserving-container
          image: "docker.io/miltonc/milton-movie-review-clf-serve:1.0.0"
          ports:
            - containerPort: 9001
              protocol: TCP
          env:
            - name: STORAGE_URI
              value: "{{inputs.artifacts.modelArtifact}}"